-- Base de Datos PostgreSQL

-- Crear la tabla Cliente
-- Descripción: Tabla que almacena los clientes de la tienda
CREATE TABLE "Cliente" (
  "run_cliente" varchar PRIMARY KEY,  -- Llave primaria, identificador único del cliente
  "nombre" varchar,  -- Nombre del cliente
  "correo" varchar,  -- Correo electrónico del cliente
  "direccion" varchar,  -- Dirección del cliente
  "telefono" bytea  -- Teléfono del cliente encriptado
);

-- Crear la tabla Boleta
-- Descripción: Tabla que almacena las boletas de compra de los clientes
CREATE TABLE "Boleta" (
  "id_boleta" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- Llave primaria, identificador único de la boleta, generado automáticamente
  "fecha" date,  -- Fecha de la boleta
  "total" integer,  -- Total de la boleta
  "run_cliente" varchar  -- Identificador del cliente asociado a la boleta
);

-- Crear la tabla Detalle_boleta
-- Descripción: Tabla que almacena los detalles de las boletas de compra
CREATE TABLE "Detalle_boleta" (
  "id_detalle_boleta" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- Llave primaria, identificador único del detalle de la boleta, generado automáticamente
  "valor" integer,  -- Valor del detalle de la boleta
  "cantidad" integer,  -- Cantidad de productos en el detalle de la boleta
  "id_boleta" integer,  -- Identificador de la boleta asociada
  "id_producto" integer,  -- Identificador del producto asociado
  "id_envio" integer  -- Identificador del envío asociado
);

-- Crear la tabla Producto
-- Descripción: Tabla que almacena los productos disponibles en la tienda
CREATE TABLE "Producto" (
  "id_producto" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- Llave primaria, identificador único del producto, generado automáticamente
  "nombre" varchar,  -- Nombre del producto
  "precio_venta" integer,  -- Precio de venta del producto
  "precio_compra" integer,  -- Precio de compra del producto
  "categoria" varchar,  -- Categoría del producto
  "rut_proveedor" varchar  -- Identificador del proveedor asociado al producto
);

-- Crear la tabla Envio
-- Descripción: Tabla que almacena los envíos de los productos a los clientes
CREATE TABLE "Envio" (
  "id_envio" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- Llave primaria, identificador único del envío, generado automáticamente
  "metodo_envio" varchar,  -- Método de envío
  "precio" varchar,  -- Precio del envío
  "fecha_envio" date,  -- Fecha de envío
  "fecha_entrega" date  -- Fecha de entrega
);

-- Añadir llave foránea en la tabla Boleta para asociarla con la tabla Cliente
ALTER TABLE "Boleta" ADD FOREIGN KEY ("run_cliente") REFERENCES "Cliente" ("run_cliente");

-- Añadir llave foránea en la tabla Detalle_boleta para asociarla con la tabla Boleta
ALTER TABLE "Detalle_boleta" ADD FOREIGN KEY ("id_boleta") REFERENCES "Boleta" ("id_boleta");

-- Añadir llave foránea en la tabla Detalle_boleta para asociarla con la tabla Producto
ALTER TABLE "Detalle_boleta" ADD FOREIGN KEY ("id_producto") REFERENCES "Producto" ("id_producto");

-- Añadir llave foránea en la tabla Detalle_boleta para asociarla con la tabla Envio
ALTER TABLE "Detalle_boleta" ADD FOREIGN KEY ("id_envio") REFERENCES "Envio" ("id_envio");
