CREATE TABLE "Cliente" (
  "run_cliente" varchar PRIMARY KEY,
  "nombre" varchar,
  "correo" varchar,
  "direccion" varchar,
  "telefono" integer
);

CREATE TABLE "Boleta" (
  "id_boleta" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha" date,
  "total" integer,
  "run_cliente" varchar
);

CREATE TABLE "Detalle_boleta" (
  "id_detalle_boleta" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "valor" integer,
  "cantidad" integer,
  "id_boleta" integer,
  "id_producto" integer,
  "id_envio" integer 
);

CREATE TABLE "Producto" (
  "id_producto" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar,
  "precio_venta" integer,
  "precio_compra" integer,
  "categoria" varchar,
  "rut_proveedor" varchar
);

CREATE TABLE "Envio" (
  "id_envio" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "metodo_envio" varchar,
  "precio" varchar,
  "fecha_envio" date,
  "fecha_entrega" date
);

ALTER TABLE "Boleta" ADD FOREIGN KEY ("run_cliente") REFERENCES "Cliente" ("run_cliente");

ALTER TABLE "Detalle_boleta" ADD FOREIGN KEY ("id_boleta") REFERENCES "Boleta" ("id_boleta");

ALTER TABLE "Detalle_boleta" ADD FOREIGN KEY ("id_producto") REFERENCES "Producto" ("id_producto");

ALTER TABLE "Detalle_boleta" ADD FOREIGN KEY ("id_envio") REFERENCES "Envio" ("id_envio");
