-- Base de Datos PostgreSQL
-- Crear la tabla Producto
-- Descripcion: Tabla que almacena los productos disponibles en el inventario
CREATE TABLE IF NOT EXISTS "Producto" (
  "id_producto" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,  -- Llave primaria, identificador único del producto, generado automáticamente
  "nombre" varchar,  -- Nombre del producto
  "precio_venta" integer,  -- Precio de venta del producto
  "precio_compra" integer,  -- Precio de compra del producto
  "categoria" varchar  -- Categoría del producto
);

-- Crear la tabla Producto_Proveedor
-- Descripcion: Tabla que almacena la relación entre productos y proveedores
CREATE TABLE IF NOT EXISTS "Producto_Proveedor" (
  "id_producto_proveedor" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,  -- Llave primaria, identificador único de la relación producto-proveedor, generado automáticamente
  "id_producto" integer,  -- Identificador del producto asociado
  "rut_proveedor" varchar  -- RUT del proveedor asociado
);

-- Crear la tabla Proveedor
-- Descripcion: Tabla que almacena los proveedores de la tienda
CREATE TABLE IF NOT EXISTS "Proveedor" (
  "rut_proveedor" varchar PRIMARY KEY,  -- Llave primaria, identificador único del proveedor
  "nombre" varchar,  -- Nombre del proveedor
  "direccion" varchar,  -- Dirección del proveedor
  "contacto" integer  -- Contacto del proveedor
);

-- Crear la tabla Stock_Sucursal
-- Descripcion: Tabla que almacena el stock de productos en cada sucursal
CREATE TABLE IF NOT EXISTS "Stock_Sucursal" (
  "stock_id" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,  -- LLave primaria, identificador único del stock, generado automáticamente
  "stock" integer,  -- Cantidad de stock
  "id_producto" integer,  -- Identificador del producto asociado
  "id_sucursal" integer  -- Identificador de la sucursal asociada
);

-- Crear la tabla Sucursal
-- Descripcion: Tabla que almacena las sucursales de la empresa
CREATE TABLE IF NOT EXISTS "Sucursal" (
  "id_sucursal" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,  -- Llave primaria, identificador único de la sucursal, generado automáticamente
  "direccion" varchar,  -- Dirección de la sucursal
  "nombre" varchar  -- Nombre de la sucursal
);

-- Crear la tabla Departamento
-- Descripcion: Tabla que almacena los departamentos de la empresa
CREATE TABLE IF NOT EXISTS "Departamento" (
  "id_departamento" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,  -- Llave primaria, identificador único del departamento, generado automáticamente
  "nombre" varchar  -- Nombre del departamento
);

-- Crear la tabla Sucursal_Departamento
-- Descripcion: Tabla que almacena la relación entre sucursales y departamentos
CREATE TABLE IF NOT EXISTS "Sucursal_Departamento" (
  "id_sucursal_departamento" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,  -- Llave primaria, identificador único de la relación sucursal-departamento, generado automáticamente
  "id_sucursal" integer,  -- Identificador de la sucursal asociada
  "id_departamento" integer  -- Identificador del departamento asociado
);

-- Añadir llave foránea en la tabla Producto_Proveedor para asociarla con la tabla Producto
ALTER TABLE "Producto_Proveedor" ADD FOREIGN KEY ("id_producto") REFERENCES "Producto" ("id_producto");

-- Añadir llave foránea en la tabla Producto_Proveedor para asociarla con la tabla Proveedor
ALTER TABLE "Producto_Proveedor" ADD FOREIGN KEY ("rut_proveedor") REFERENCES "Proveedor" ("rut_proveedor");

-- Añadir llave foránea en la tabla Stock_Sucursal para asociarla con la tabla Producto
ALTER TABLE "Stock_Sucursal" ADD FOREIGN KEY ("id_producto") REFERENCES "Producto" ("id_producto");

-- Añadir llave foránea en la tabla Stock_Sucursal para asociarla con la tabla Sucursal
ALTER TABLE "Stock_Sucursal" ADD FOREIGN KEY ("id_sucursal") REFERENCES "Sucursal" ("id_sucursal");

-- Añadir llave foránea en la tabla Sucursal_Departamento para asociarla con la tabla Sucursal
ALTER TABLE "Sucursal_Departamento" ADD FOREIGN KEY ("id_sucursal") REFERENCES "Sucursal" ("id_sucursal");

-- Añadir llave foránea en la tabla Sucursal_Departamento para asociarla con la tabla Departamento
ALTER TABLE "Sucursal_Departamento" ADD FOREIGN KEY ("id_departamento") REFERENCES "Departamento" ("id_departamento");