CREATE TABLE "Producto" (
  "id_producto" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar,
  "precio_venta" integer,
  "precio_compra" integer,
  "categoria" varchar
);

CREATE TABLE "Producto_Proveedor" (
  "id_producto_proveedor" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_producto" integer,
  "rut_proveedor" varchar
);

CREATE TABLE "Proveedor" (
  "rut_proveedor" varchar PRIMARY KEY,
  "nombre" varchar,
  "direccion" varchar,
  "contacto" integer
);

CREATE TABLE "Stock_Sucursal" (
  "stock_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "stock" integer,
  "producto_id" integer,
  "sucursal_id" integer
);

CREATE TABLE "Sucursal" (
  "id_sucursal" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "direccion" varchar,
  "nombre" varchar
);

CREATE TABLE "Departamento" (
  "id_departamento" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar
);

CREATE TABLE "Sucursal_Departamento" (
  "id_sucursal_departamento" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_sucursal" integer,
  "id_departamento" integer
);

ALTER TABLE "Producto_Proveedor" ADD FOREIGN KEY ("id_producto") REFERENCES "Producto" ("id_producto");

ALTER TABLE "Producto_Proveedor" ADD FOREIGN KEY ("rut_proveedor") REFERENCES "Proveedor" ("rut_proveedor");

ALTER TABLE "Stock_Sucursal" ADD FOREIGN KEY ("producto_id") REFERENCES "Producto" ("id_producto");

ALTER TABLE "Stock_Sucursal" ADD FOREIGN KEY ("sucursal_id") REFERENCES "Sucursal" ("id_sucursal");

ALTER TABLE "Sucursal_Departamento" ADD FOREIGN KEY ("id_sucursal") REFERENCES "Sucursal" ("id_sucursal");

ALTER TABLE "Sucursal_Departamento" ADD FOREIGN KEY ("id_departamento") REFERENCES "Departamento" ("id_departamento");
